try {
    Int8Array();
    console.log("no exception");
} catch (e) {
    console.log(e.name);
}
